### ISSUE TITLE
Proposal: Building institutional computational genomics capacity (de novo)

### ISSUE THREAD

**Issue by serahkiburu** [carpentrycon/carpentryconhome-proposals#11]
### Session details

* Session type: Breakout Session 

* Keywords: Genomics, Capacity, Communities of Practice, MOOC, Study Group, Self-learning, Next-Generation Sequencing (NGS) Data 

* Permission to record this session: PENDING 

### Abstract

There is a growing gap between the accumulation of big data and researchers’ knowledge about how to use it effectively. Furthermore, there seems to be great interest from the Carpentries community to learn and teach genomics. South Africa boasts 26 public universities each conducting research in areas where genomics techniques are (or can be) applied to answer questions related to health, food, environmental issues, and/or agriculture. Currently, only nine of these universities offer formal undergraduate or postgraduate training programmes in bioinformatics or computational genomics. The North-West University (NWU) isn't one of these nine. For that reason, we explored various avenues for building institutional genomics capacity. I would like to present this topic in the form of a breakout session at #CarpentryCon2020Madison and discuss the results and challenges for each approach, as was experienced by our institution’s researchers. I would also like other people in the field of genomics to tells us how they build genomics capacity at their institutions. Together we might come up with feasible solutions to "teach people how to fish".

### Personal details

* Name or pseudoname of the session lead: Bianca Peterson

* Co-leads' names (we recommend involving 2 helpers/co-leads): PENDING

* Email or other ways to contact the session leads/co-leads: PENDING

* Country of residence and/or compatible Time Zones (provide options): PENDING

* Would you like to present this multiple times, in other time zones: PENDING

* Would you like to volunteer to be listed as a wrangler/host for your time zone: PENDING  

### Is there any help you would like to invite from the community? Please provide below in bullet points.

* PENDING

* Other comment: WRITE HERE

**Comment by serahrono** [comment]
Hi @BinxiePeterson, please add details about your session to the sections with information pending above by editing [the issue text](https://github.com/carpentrycon/carpentryconhome-proposals/issues/11#issue-623152865)

**Comment by serahrono** [comment]
Hi @BinxiePeterson, thanks for agreeing to run your workshop remotely for CarpentryCon@Home.  Please add details about your session to the sections with information pending above by editing the [issue text](https://github.com/carpentrycon/carpentryconhome-proposals/issues/11#issue-623152865)

**Comment by serahkiburu** [comment]
Hi @BinxiePeterson, thanks for agreeing to run your breakout session remotely for CarpentryCon@Home.  Please add details about your session to the sections with information pending above by editing the [issue text](https://github.com/carpentrycon/carpentryconhome-proposals/issues/11#issue-623152865)

**Comment by JasonJWilliamsNY** [comment]
I am willing to be assigned as an issue monitor/facilitator

**Comment by serahkiburu** [comment]
closing this issue, as @BinxiePeterson has opened a new one under #58
