### ISSUE TITLE
Proposal: How to prevent and kick burnout to the curb

### ISSUE THREAD

**Issue by serahkiburu** [carpentrycon/carpentryconhome-proposals#13]
### Session details

* Session type: Breakout session 

* Keywords: burnout, stress, stress management, relaxation, efficiency 

* Permission to record this session: PENDING 

### Abstract

Since becoming part of the Carpentries' community, I can't imagine what my life was like before. I have learned so many things in the past few year, even though it was a long, hard road and many lessons were learned. Burnout was a reality for me, and I am certain that it is for many others as well. I would thus like to propose a breakout session where people can share their experiences, challenges, and solutions to preventing/treating burnout. We not only want an active community, but a healthy one.

### Personal details

* Name or pseudoname of the session lead: Bianca Peterson

* Co-leads' names (we recommend involving 2 helpers/co-leads): PENDING

* Email or other ways to contact the session leads/co-leads: PENDING

* Country of residence and/or compatible Time Zones (provide options): PENDING

* Would you like to present this multiple times, in other time zones: PENDING

* Would you like to volunteer to be listed as a wrangler/host for your time zone: WRITE HERE  

### Is there any help you would like to invite from the community? Please provide below in bullet points.

* PENDING

* Other comment: WRITE HERE

**Comment by serahkiburu** [comment]
Hi @BinxiePeterson, thanks for agreeing to run your breakout session remotely for CarpentryCon@Home. Please add details about your session to the sections with information pending above by editing the [issue text](https://github.com/carpentrycon/carpentryconhome-proposals/issues/13#issue-623162402).

**Comment by ChristinaLK** [comment]
@BinxiePeterson if you're still interested in running this session for CarpentryCon @ Home, let us know what times you'd like and if you need any help/other contributors.

**Comment by serahkiburu** [comment]
closing this, as @BinxiePeterson has opened a related one here #59
