### ISSUE TITLE
How to Run a Meeting

### ISSUE THREAD

**Issue by gvwilson** [carpentrycon/carpentryconhome-proposals#43]
### Session details

* Session type: other

* Keywords: community management; teamwork; time management.

* Permission to record this session: Yes.

### Abstract

The Carpentries exist so that people don't have to teach themselves how to program, but ironically, most members of the Carpentry community have had to learn how to coordinate groups on their own. This talk lays out ten simple rules for running an effective meeting, and will help you get more done in less time and with less pain.

### Personal details

* Name or pseudoname of the session lead: Greg Wilson

* Co-leads' names (we recommend involving 2 helpers/co-leads): N/A

* Email or other ways to contact the session leads/co-leads: gvwilson@third-bit.com

* Country of residence and/or compatible Time Zones (provide options): Eastern time (Toronto)

* Would you like to present this multiple times, in other time zones: If desired; I can be available whenever is convenient.

* Would you like to volunteer to be listed as a wrangler/host for your time zone: No

### Is there any help you would like to invite from the community?

N/A

* Other comment: N/A

**Comment by serahkiburu** [comment]
Hi @gvwilson, the organising committee reviewed this session proposal and had this to say:

>This skill-up session on how to effectively run meetings will be an invaluable addition to the conference. Because many in the community recently started working remotely, some more specific details on topics like managing people, resources, conflict, and communication that will be covered in this session will be much appreciated if added to the abstract beforehand.

We are looking forward to your session, and more details i.e. around scheduling will be shared with you in the coming days. Let me know if I can answer any questions or clarify anything for the time being.
