### ISSUE TITLE
TODO: Create list of labels for issues in this repo

### ISSUE THREAD

**Issue by serahkiburu** [carpentrycon/carpentryconhome-proposals#6]
As per @malvikasharan's request in https://github.com/carpentrycon/carpentryconhome-proposals/pull/1 we need to make a few labels for proposal type, so issues can be tagged by session type.

**Comment by serahkiburu** [comment]
from May 18 committee meeting:
we need labels to denote:
- the session type i.e. breakout, workshop
- the status of review for each proposal in a standalone issue i.e. WIP, ready for review, under review, scheduled etc
- the scheduling status of a proposal i.e. scheduled
- timezone labels, grouped by region i.e. Australasia, EMEA, US East Coast/ WC South America, etc. See suggested regions [here](https://github.com/carpentrycon/carpentryconhome-proposals#relative-time-zones)

**Comment by serahrono** [comment]
@kerchner here's the issue on labels

**Comment by mkuzak** [comment]
here are the labels I came up with, based on discussions:
# session types
session breakout
session skill-up
session panel
session social
session sprint
session other

# status
WIP
ready for review
under review
scheduled

# timezone
UTC -12 to -7
UTC -06 to -01
UTC +-00 to +05:45
UTC +06 to +11:30
UTC +12 to +14

**Comment by ChristinaLK** [comment]
^^ for the timezones, can we use the labels from the README? (oceania, europe, africa, etc.)

**Comment by kerchner** [comment]
To reduce label clutter when people are submitting proposals, I've deleted a few labels that probably don't apply here:
- bug
- documentation
- enhancement
- good first issue.

We can always add back later if there is a need.

Do folks feel that milestones will be a good way to organize "sprints" of sessions?  I would propose milestones for:
- Schedule backlog
- Week 1 ( <-- weeks get a dates as soon as we build out a schedule for CC@H) 
- Week 2
etc.

**Comment by ChristinaLK** [comment]
@kerchner that sounds good to me!!

**Comment by mkuzak** [comment]
@ChristinaLK about the time zones, that's what I wanted to do :) but I cannot find the right unique names for the time zone ranges, eg. do we use Africa or Europe?

**Comment by mkuzak** [comment]
@kerchner that's great

**Comment by ChristinaLK** [comment]
Can we combine? use a dash or a slash to separate?

**Comment by mkuzak** [comment]
What about following?
`Oceania & North America`
`North & South America`
`Asia`
`Asia & Oceania`
there will be more detailed information in the description of the label

**Comment by kerchner** [comment]
- [x] Created Milestones (we can edit dates once we have them.  And/or change to 2-week sprints, etc.)

**Comment by mkuzak** [comment]
I updated timezone labels. Let me know if you agree on those.

**Comment by ChristinaLK** [comment]
I think this looks good @mkuzak !

**Comment by kerchner** [comment]
How did Oceania get put together with North America?  Wouldn't Oceania be closer to East Asia?

**Comment by mkuzak** [comment]
There are two ranges covering Oceania, `Oceania & North America` and `Asia & Oceania`
